/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EZEA2
 */
public class GUIEliminarDato extends javax.swing.JFrame {

    /**
     * Creates new form GUIEliminarVendedor
     */
    Logic lo;
    String table;
    DefaultTableModel tablita;
    long thisDNI;
    int length;
    DB data;
    
    public GUIEliminarDato(DB _data,String _table,long _thisDNI) throws SQLException {
        thisDNI=_thisDNI;
        init(_data,_table);
    }
    
    public GUIEliminarDato(DB _data,String _table) throws SQLException {
        init(_data,_table);
    }
    
    private void init(DB _data,String _table) throws SQLException{
        initComponents();
        FlatLightLaf.setup();
        setLocationRelativeTo(null);
        
        txtEntrada.grabFocus();
       
        lo=new Logic(_data);
        data=_data;
        table=_table;
        
        switch(table){
            case "empleados":{
                txtObjeto.setText("vendedor");
                txtEntradaLabel.setText("DNI:");
                break;
            }
            case "clientes":{
                txtObjeto.setText("cliente");
                txtEntradaLabel.setText("DNI:");
                break;
            }
            case "productos":{
                txtObjeto.setText("producto");
                txtEntradaLabel.setText("ID:");
                break;
            }
        }
        
        Action action = new AbstractAction(){ //para detectar el enter
            @Override
            public void actionPerformed(ActionEvent e)
            {
                btnEliminarActionPerformed(e);
            }
        };
        txtEntrada.addActionListener(action);
        
        tablita=new DefaultTableModel();
        String names[]=lo.getColumnNames(table);
        length=names.length;
        
        for(int i=1;i<length;i++){
            if(table.equals("empleados") && (i<3)) continue; //escondo num, user y password
            tablita.addColumn(names[i]);
        }
        tabla.setModel(tablita);
        
        cargarDatos();
    }
    
    private void cargarDatos() throws SQLException{
        String info[];
        
        
        for(int i=1;i<=data.getRowCount(table);i++){
            info=data.getRow(table,i); 
            
            if(table.equals("empleados")){ //esconder num, user y password
                for(int j=0;j<info.length-3;j++){
                    info[j]=info[j+3];
                }
                
                if("1".equals(info[info.length-4])) info[info.length-4]="Si";
                else info[info.length-4]="No";
            }
            else{ //esconder num
                for(int j=0;j<info.length-1;j++){
                    info[j]=info[j+1];
                }
            }
            
            tablita.addRow(info); //agregar que solo muestre x columnas y no todas
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtEntradaLabel = new javax.swing.JLabel();
        txtEntrada = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        txtObjeto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Eliminar");

        txtEntradaLabel.setText("DNI:");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtObjeto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtObjeto.setText("Objeto");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtEntradaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnEliminar))
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtObjeto)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtObjeto))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEntradaLabel)
                            .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        switch(table){
            case "empleados":{
                if(lo.eliminarVendedor(txtEntrada.getText(),thisDNI)) dispose();
                break;
            }
            case "clientes":{
                if(lo.eliminarCliente(txtEntrada.getText())) dispose();
                break;
            }
            case "productos":{
                if(lo.eliminarProducto(txtEntrada.getText())) dispose();
                break;
            }
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtEntrada;
    private javax.swing.JLabel txtEntradaLabel;
    private javax.swing.JLabel txtObjeto;
    // End of variables declaration//GEN-END:variables
}
