/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion;

import com.formdev.flatlaf.FlatLightLaf;
import java.sql.SQLException;

/**
 *
 * @author EZEA2
 */
public class GUIMenu extends javax.swing.JFrame {

    /**
     * Creates new form GUIMenu
     */
    
    DB data;
    Logic lo;
    String user;
    Vendedor vend;
    
    public GUIMenu(String _user,DB _data) throws SQLException {
        initComponents();
        FlatLightLaf.setup();
        setLocationRelativeTo(null);
        new Utilidades().scaleImage(logo);

        data=_data;
        user=_user;
        vend=data.createObjectVendedor(_user);
        lo=new Logic(data);
        
        txtNombre.setText(vend.getName());
        txtApellido.setText(vend.getLastname());
        if(vend.isAdmin()){
            if("admin".equals(user)) txtApellido.setVisible(false);
        }
        else {
            btnNuevoVendedor.setEnabled(false);
            btnEliminarVendedor.setEnabled(false);
        }
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        txtApellido = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnNuevaVenta = new javax.swing.JMenuItem();
        btnNuevoProducto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnNuevoVendedor = new javax.swing.JMenuItem();
        btnEliminarVendedor = new javax.swing.JMenuItem();
        btnCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Bienvenido, ");

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtNombre.setText("Nombre");

        txtApellido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtApellido.setText("Apellido");

        jMenu1.setText("Ventas");

        btnNuevaVenta.setText("Nueva venta");
        btnNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaVentaActionPerformed(evt);
            }
        });
        jMenu1.add(btnNuevaVenta);

        btnNuevoProducto.setText("Añadir producto");
        jMenu1.add(btnNuevoProducto);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Configuracion");

        btnNuevoVendedor.setText("Añadir vendedor");
        btnNuevoVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoVendedorActionPerformed(evt);
            }
        });
        jMenu2.add(btnNuevoVendedor);

        btnEliminarVendedor.setText("Eliminar vendedor");
        btnEliminarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarVendedorActionPerformed(evt);
            }
        });
        jMenu2.add(btnEliminarVendedor);

        btnCerrarSesion.setText("Cerrar sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        jMenu2.add(btnCerrarSesion);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(458, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtApellido)
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre)
                    .addComponent(txtApellido))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaVentaActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        new GUILogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnNuevoVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoVendedorActionPerformed
        // TODO add your handling code here:
        new GUINuevoVendedor(data).setVisible(true);
    }//GEN-LAST:event_btnNuevoVendedorActionPerformed

    private void btnEliminarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarVendedorActionPerformed
        // TODO add your handling code here:
        new GUIEliminarVendedor(data).setVisible(true);
    }//GEN-LAST:event_btnEliminarVendedorActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCerrarSesion;
    private javax.swing.JMenuItem btnEliminarVendedor;
    private javax.swing.JMenuItem btnNuevaVenta;
    private javax.swing.JMenuItem btnNuevoProducto;
    private javax.swing.JMenuItem btnNuevoVendedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel txtApellido;
    private javax.swing.JLabel txtNombre;
    // End of variables declaration//GEN-END:variables
}
